### ISSUE TITLE
Duplicate on bmsql_oorder_idx1

### ISSUE THREAD

**Issue by williamsd-ppb** [pgsql-io/benchmarksql#19]
Converted to use Informix and seeing the following exception.

13:46:21,577 [Thread-43] ERROR  jTPCCTData : Unexpected SQLException in NEW_ORDER
13:46:21,577 [Thread-43] ERROR  jTPCCTData : Could not insert new row - duplicate value in a UNIQUE INDEX column (Unique Index:bmsql_oorder_idx1).(-239) ISAM error:  duplicate value for a record with unique key.(-100)
java.sql.SQLException: Could not insert new row - duplicate value in a UNIQUE INDEX column (Unique Index:bmsql_oorder_idx1).(-239) ISAM error:  duplicate value for a record with unique key.(-100)
        at com.informix.util.IfxErrMsg.buildExceptionWithMessage(IfxErrMsg.java:416)
        at com.informix.util.IfxErrMsg.buildIsamException(IfxErrMsg.java:401)
        at com.informix.jdbc.IfxSqli.addException(IfxSqli.java:3021)
        at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java:3272)
        at com.informix.jdbc.IfxSqli.dispatchMsg(IfxSqli.java:2269)
        at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2194)
        at com.informix.jdbc.IfxSqli.executeCommand(IfxSqli.java:813)
        at com.informix.jdbc.IfxResultSet.executeUpdate(IfxResultSet.java:225)
        at com.informix.jdbc.IfxStatement.executeUpdateImpl(IfxStatement.java:958)
        at com.informix.jdbc.IfxPreparedStatement.executeUpdate(IfxPreparedStatement.java:322)
        at jTPCCTData.executeNewOrder(jTPCCTData.java:530)
        at jTPCCTData.execute(jTPCCTData.java:136)
        at jTPCCTerminal.executeTransactions(jTPCCTerminal.java:328)
        at jTPCCTerminal.run(jTPCCTerminal.java:146)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: ISAM error:  duplicate value for a record with unique key.
        at com.informix.util.IfxErrMsg.buildExceptionWithMessage(IfxErrMsg.java:416)
        at com.informix.util.IfxErrMsg.buildException(IfxErrMsg.java:397)
        at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:371)
        at com.informix.jdbc.IfxSqli.receiveError(IfxSqli.java:3276)
        ... 11 more

**Comment by luss** [comment]
Does it happen when running just one row or is this an issue under load?
